app = "your-app-name"  # Замени на уникальное имя твоего приложения
primary_region = "ams"  # Выбери регион, например, Amsterdam (ams)

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
